/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgendarRouteImport } from './routes/_authenticated/agendar'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedMotoristaRouteImport } from './routes/_authenticated/motorista'
import { Route as AuthenticatedPainelMasterRouteImport } from './routes/_authenticated/painel-master'
import { Route as AuthenticatedPetsPetIdRouteImport } from './routes/_authenticated/pets.$petId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendarRoute = AuthenticatedAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoristaRoute = AuthenticatedMotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelMasterRoute =
  AuthenticatedPainelMasterRouteImport.update({
    id: '/painel-master',
    path: '/painel-master',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetsPetIdRoute = AuthenticatedPetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/loja': typeof LojaRoute
  '/painel': typeof PainelRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/conta': typeof AuthenticatedContaRoute
  '/motorista': typeof AuthenticatedMotoristaRoute
  '/painel-master': typeof AuthenticatedPainelMasterRoute
  '/pets/$petId': typeof AuthenticatedPetsPetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/loja': typeof LojaRoute
  '/painel': typeof PainelRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/conta': typeof AuthenticatedContaRoute
  '/motorista': typeof AuthenticatedMotoristaRoute
  '/painel-master': typeof AuthenticatedPainelMasterRoute
  '/pets/$petId': typeof AuthenticatedPetsPetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/loja': typeof LojaRoute
  '/painel': typeof PainelRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agendar': typeof AuthenticatedAgendarRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/motorista': typeof AuthenticatedMotoristaRoute
  '/_authenticated/painel-master': typeof AuthenticatedPainelMasterRoute
  '/_authenticated/pets/$petId': typeof AuthenticatedPetsPetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/loja'
    | '/painel'
    | '/redefinir-senha'
    | '/admin'
    | '/agendar'
    | '/conta'
    | '/motorista'
    | '/painel-master'
    | '/pets/$petId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/loja'
    | '/painel'
    | '/redefinir-senha'
    | '/admin'
    | '/agendar'
    | '/conta'
    | '/motorista'
    | '/painel-master'
    | '/pets/$petId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrinho'
    | '/loja'
    | '/painel'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/agendar'
    | '/_authenticated/conta'
    | '/_authenticated/motorista'
    | '/_authenticated/painel-master'
    | '/_authenticated/pets/$petId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  LojaRoute: typeof LojaRoute
  PainelRoute: typeof PainelRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agendar': {
      id: '/_authenticated/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AuthenticatedAgendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorista': {
      id: '/_authenticated/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof AuthenticatedMotoristaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-master': {
      id: '/_authenticated/painel-master'
      path: '/painel-master'
      fullPath: '/painel-master'
      preLoaderRoute: typeof AuthenticatedPainelMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/$petId': {
      id: '/_authenticated/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof AuthenticatedPetsPetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendarRoute: typeof AuthenticatedAgendarRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedMotoristaRoute: typeof AuthenticatedMotoristaRoute
  AuthenticatedPainelMasterRoute: typeof AuthenticatedPainelMasterRoute
  AuthenticatedPetsPetIdRoute: typeof AuthenticatedPetsPetIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendarRoute: AuthenticatedAgendarRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedMotoristaRoute: AuthenticatedMotoristaRoute,
  AuthenticatedPainelMasterRoute: AuthenticatedPainelMasterRoute,
  AuthenticatedPetsPetIdRoute: AuthenticatedPetsPetIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  LojaRoute: LojaRoute,
  PainelRoute: PainelRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
